- name: Instalar puppet no centos
  shell: rpm -Uvh '/tmp/puppet6-release-el-7.noarch.rpm'
  become: true
  ignore_errors: True
  when: ansible_distribution|lower == "centos"

- name: Instalar Puppet-agent no CentOS
  yum:
    name: puppet-agent
    state: present
  when: ansible_distribution|lower == "centos"
