- name: Baixar o Puppet no Ubuntu
  get_url:
    url: https://apt.puppetlabs.com/puppet6-release-xenial.deb
    dest: /tmp/puppet.deb
  when: ansible_os_family == "Debian"

- name: Baixar o Puppet no CentOS
  get_url:
    url: https://yum.puppet.com/puppet6/puppet6-release-el-7.noarch.rpm
    dest: /tmp/puppet.rpm
  when: ansible_os_family == "RedHat"

#- name: Baixar o Puppet no Ubuntu
#  get_url:
#    url: https://apt.puppetlabs.com/puppet6-release-xenial.deb
#    dest: /tmp
#    mode: 0440
#
#- name: Baixar o Puppet no CentOS
#  get_url:
#    url: https://yum.puppet.com/puppet6/puppet6-release-el-7.noarch.rpm
#    dest: /tmp
#    mode: 0440
