---
- hosts: all
  become: yes  
  tasks:
  - package: 
      name: ['telnet','curl','wget']
      state: present
  - package:
      name: httpd
      state: present
    when: ansible_distribution|lower == 'centos'
  - package:
      name: apache2
      state: present
    when: ansible_distribution|lower != 'centos'

...
