---
- name: Playbook do side kid
  hosts: all
  become: yes
  vars: 
    usuario: dick_grayson      
  tasks:
  - name: Verificar memoria
    command: free -h

  - name: Verificando Usuário
    shell: cat /etc/passwd | grep vagrant

  - name: Remover o Apache2
    apt: 
      name: apache2
      state: absent
      update_cache: yes
    when: ansible_distribution|lower == "ubuntu"

  - name: Remover HTTPD
    yum:
      name: httpd
      state: absent
    when: ansible_distribution|lower == "centos"  
  
  - name: Garantir hosts
    lineinfile: 
      path: /etc/hosts
      create: yes
      line: "{{ item }}" 
    loop: 
    - "192.168.99.10 devops.salas4linux.com.br devops"
    - "192.168.99.20 docker.salas4linux.com.br devops"
    - "192.168.99.30 automation.salas4linux.com.br devops"
    
  - name: Criando Usuário
    user: name={{ usuario }} shell=/bin/bash create_home=yes

  - name: Copiar arquivo 
    copy: 
      src: teste.txt
      dest: /tmp/novo_nome.txt

  - name: Isntalar o NGINX
    package: 
      name: nginx
      state: present
    notify: restart

  handlers:
    - name: restart
      systemd: 
        name: nginx
        state: restarted

...
