- name: Parar o HTTPD
  systemd:
    name: httpd
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Remove o HTTPD
  package:
    name: httpd*
    state: absent
  when: ansible_os_family == "RedHat"
